import 'package:app_tracking_transparency/app_tracking_transparency.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:permission_handler/permission_handler.dart';

import '../config/providers.dart';
import '../error/failure.dart';
import '../error/result.dart';
import '../network/firebase_error_mapper.dart';
import '../utils/logger.dart';

/// Bridges the app to the third-party offerwall provider.
///
/// Two responsibilities:
///  1. **Usage-tracking consent** — offerwall app-install/engagement tasks are
///     verified using device usage signals, so we transparently ask the user
///     for tracking authorisation (ATT on iOS; the app-usage/`PACKAGE_USAGE_STATS`
///     access hint on Android) before opening the wall. Nothing is tracked
///     until the user grants it.
///  2. **Signed wall URL** — the offerwall URL embeds the user's subid and an
///     HMAC signature. It is generated by the `getOfferwallUrl` Cloud Function
///     (the signing secret never ships in the app), guaranteeing postbacks can
///     be attributed and can't be forged.
class OfferwallService {
  OfferwallService(this._functions);

  final FirebaseFunctions _functions;

  /// The current tracking authorisation status (iOS ATT; Android returns
  /// authorized by default unless usage-access is required by a task).
  Future<TrackingStatus> trackingStatus() =>
      AppTrackingTransparency.trackingAuthorizationStatus;

  /// Requests tracking consent. Returns true if granted/authorised.
  Future<bool> requestTrackingConsent() async {
    try {
      final current =
          await AppTrackingTransparency.trackingAuthorizationStatus;
      if (current == TrackingStatus.notDetermined) {
        // Small delay recommended by Apple so the prompt isn't shown mid-launch.
        await Future<void>.delayed(const Duration(milliseconds: 200));
        final result =
            await AppTrackingTransparency.requestTrackingAuthorization();
        return result == TrackingStatus.authorized;
      }
      return current == TrackingStatus.authorized;
    } catch (e, s) {
      log.w('Tracking consent request failed', e, s);
      return false;
    }
  }

  /// Whether the app has been granted Android usage-access (used to verify some
  /// engagement offers). On iOS this always returns true.
  Future<bool> hasUsageAccess() async {
    final status = await Permission.appTrackingTransparency.status;
    return status.isGranted || status.isLimited;
  }

  /// Fetches a signed, per-session offerwall URL for the current user.
  Future<Result<String>> getWallUrl({String placement = 'main'}) async {
    try {
      final callable = _functions.httpsCallable('getOfferwallUrl');
      final res = await callable.call<Map<String, dynamic>>({
        'placement': placement,
      });
      final url = (res.data['url'] ?? '').toString();
      if (url.isEmpty) {
        return const Result.failure(
          OperationFailure('Offerwall is unavailable right now.',
              code: 'offerwall/unavailable'),
        );
      }
      return Result.success(url);
    } catch (e, s) {
      log.e('getWallUrl failed', e, s);
      return Result.failure(FirebaseErrorMapper.map(e, s));
    }
  }
}

final offerwallServiceProvider = Provider<OfferwallService>((ref) {
  return OfferwallService(ref.watch(functionsProvider));
});
